version: '3'

tasks:
  all:
    cmds:
      - task: cleanup
      - task: build
      - task: package
      - task: adb
    silent: true

  build:
    cmds:
      - rm -rf build
      - mkdir -p build
      - mkdir -p build/lib
      - docker buildx build --platform=linux/arm64 -t retro-console-arm64 -f Dockerfile .
    silent: true

  package:
    cmds:
      - docker create --name extract retro-console-arm64
      - docker cp extract:/build/cannoliOS build/cannoliOS
      - docker cp extract:/build/igm build/igm
      - docker cp extract:/usr/lib/aarch64-linux-gnu/libSDL2_gfx-1.0.so.0.0.2 build/lib/libSDL2_gfx-1.0.so.0
      - rm -rf build/System || true
      - mkdir -p build/System
      - mkdir -p build/System/lib
      - mkdir -p build/System/fonts
      - cp build/cannoliOS build/igm launch.sh build/System
      - cp resources/configs/config-brick.json build/System/config.json
      - cp -R build/lib build/System
      - cp fonts/unifont-16.0.04.otf build/System/fonts/Cannoli.ttf
      - cp -R resources/ build/System/resources
    silent: true

  cleanup:
    cmds:
      - docker rm extract || true
    silent: true

  adb:
    cmds:
      - adb push build/System /mnt/SDCARD
      - adb shell killall cannoliOS igm retroarch
      - say Finished deploying Cannoli OS!
    silent: true

  i18n:
    cmds:
      - adb push resources /mnt/SDCARD/System/resources/i18n